
CREATE TABLE QUARTO (
	ID_QUARTO SERIAL PRIMARY KEY,
	DESCRICAO VARCHAR(45) NOT NULL,
	VISTA BOOLEAN DEFAULT FALSE,
	DIARIA NUMERIC(10,2) NOT NULL,
	LEITOS INTEGER NOT NULL,
	STATUS VARCHAR(45) NOT NULL
);

CREATE TABLE HOSPEDE (
	ID_HOSPEDE SERIAL PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	TELEFONE VARCHAR(25) NOT NULL,
	CPF VARCHAR(25) NOT NULL,
	RG VARCHAR(25) NOT NULL,
	NASCIMENTO TIMESTAMP NOT NULL
);

CREATE TABLE RESERVA (
	ID_RESERVA SERIAL PRIMARY KEY,
	DATA_ENTRADE TIMESTAMP NOT NULL,
	DATA_SAIDA TIMESTAMP,
	STATUS VARCHAR(45) NOT NULL,
	TOTAL NUMERIC(10,2) NOT NULL,
	ID_HOSPEDE INTEGER NOT NULL,
	ID_QUARTO INTEGER NOT NULL,
	FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO (ID_QUARTO),
	FOREIGN KEY (ID_HOSPEDE) REFERENCES HOSPEDE (ID_HOSPEDE)
);
